- id: language-checker
  name: 'language-checker'
  entry: scripts/pre-commit.sh
  language: 'script'
  description: "Runs `language-checker`"
- id: language-checker-from-source
  name: 'language-checker'
  entry: language-checker
  args: [--exit-1-on-failure]
  # The 'go' binary on your path must be at least version 1.18.
  language: 'golang'
  description: "Runs `language-checker`, building it from source on demand"
