# First: Install pre-commit https://pre-commit.com/#install
# Then, run `pre-commit install`
repos:
  - repo: git://github.com/caitlinelfring/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: golangci-lint
      - id: go-mod-tidy
  # Might not be the best idea since a development version of language-checker might prevent commits
  # - repo: git://github.com/jdstrand/language-checker
  #   rev: main
  #   hooks:
  #     - id: language-checker
